os:
    - linux
language: generic
sudo: required
dist: trusty

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
    - postgresql-9.6-postgis-2.3-scripts

services:
  - postgresql

osx_image: xcode10.2
install:
    - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"

env:
  - PSQL_DATABASE_URL=postgresql://postgres:@localhost:5432/travis_ci_test
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
script:
    - swift test
